export const REQUEST_REVERSE_HISTORY = "REQUEST_REVERSE_HISTORY";
export const REQUEST_REVERSE_HISTORY_SUCCEEDED = "REQUEST_REVERSE_HISTORY_SUCCESS";
export const REQUEST_REVERSE_HISTORY_FAILED = "REQUEST_REVERSE_HISTORY_FAILED";
export const REVERSE_PHRASE = "REVERSE_PHRASE";
export const REVERSE_PHRASE_SUCCEEDED = "REVERSE_PHRASE_SUCCEEDED";
export const REVERSE_PHRASE_FAILED = "REVERSE_PHRASE_FAILED";
